#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
	printf "\033c"
	echo -e ""
	{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
	echo -e ""
	echo -e '\e[38;5;82m' "You must run \"flatjak\" script using \"sudo\" or as the root user."
	echo -e '\e[38;5;82m' "Hint : \"sudo flatjak\" or \"su -c 'flatjak'\""
	echo -e ""
	{ for i in {16..51} {51..16}; do echo -en "\e[38;5;${i}m#\e[0m"; done; echo; }
	echo -e ""
	tput sgr0
	exit 1
fi

printf "\033c"

if ! type flatpak >/dev/null 2>&1; then
	apt-get --yes update
	apt-get --yes install flatpak
	if ! type flatpak-xdg-utils >/dev/null 2>&1; then
		apt-get --yes update
		apt-get --yes install flatpak-xdg-utils
		if ! type xdg-desktop-portal >/dev/null 2>&1; then
			apt-get --yes update
			apt-get --yes install xdg-desktop-portal
			if ! type xdg-desktop-portal-gtk >/dev/null 2>&1; then
				apt-get --yes update
				apt-get --yes install xdg-desktop-portal-gtk
				if type gnome-software >/dev/null 2>&1; then
					apt-get --yes update
					apt-get --yes install gnome-software-plugin-flatpak xdg-desktop-portal-gnome
					if type plasma-discover >/dev/null 2>&1; then
						apt-get --yes update
						apt-get --yes install plasma-discover-backend-flatpak xdg-desktop-portal-kde
						if type ubuntukylin-keyring >/dev/null 2>&1; then
							apt-get --yes update
							apt-get --yes install ubuntu-kylin-software-center
						fi
					fi
				fi
			fi
		fi
	fi
fi

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

printf "\033c"

echo -e ""
echo -e "Flatpak is installed with required desktop integrations and the Flathub repository."
echo -e ""
echo -e "If Flatpak applications don't show up in GNOME Software or Discover, please reboot."
echo -e ""
read -rsp $'Press any key to continue...\n' -n1

printf "\033c"
exit 0
